services:
  web:
    build: .
    image: oh-my-dog-web
    container_name: ohmydog-web
    volumes:
      - ./OhMyDog-Web:/var/lib/omdweb
    ports:
      - "3000:3000"
    networks:
      - omd-network

networks:
  omd-network:
    driver: bridge
